export const SET_RACERS = 'SET_RACERS';
export const SET_RACERS_LOADING = 'SET_RACERS_LOADING';

export const SET_RACER = 'SET_RACER';
export const SET_RACER_LOADING = 'SET_RACER_LOADING';

export const SET_RACES = 'SET_RACES';
export const SET_RACES_LOADING = 'SET_RACES_LOADING';
